apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 8080}]'
    alb.ingress.kubernetes.io/group.name: "kong-ingress"
    alb.ingress.kubernetes.io/subnets: {{ .Values.ingress.subnet }}
    {{ if .Values.ingress.kong_sg }}
    alb.ingress.kubernetes.io/security-groups: {{ .Values.ingress.kong_sg }}
    {{ end }}
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
    meta.helm.sh/release-name: helm-ing
    meta.helm.sh/release-namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  name: {{ .Values.ingress.ingName }}-ingress
  namespace: {{ $.Release.Namespace }}
spec:
  rules:
    {{ if .Values.ingress.konga_host }}
    - host: {{ .Values.ingress.konga_host }}
      http:
    {{ else }}
    - http:
    {{ end }}
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-konga
                port:
                  number: 80